### ISSUE TITLE
Use of uninitialized value $_ in delete at Alien/Base/ModuleBuild.pm line 740.

### ISSUE THREAD

**Issue by wbraswell** [Perl5-Alien/Alien-Base#171] opened 2017-01-11 03:25 UTC
This is a seemingly non-fatal bug, which appears in more than one operating system...

Use of uninitialized value $_ in delete at Alien/Base/ModuleBuild.pm line 740.

In Windows:
https://ci.appveyor.com/project/wbraswell/rperl/build/1.0.319#L3146

In Solaris:
http://www.cpantesters.org/cpan/report/da23f76a-d717-11e6-9aca-9a525a7089b8

**Comment by plicease** [comment] 2017-01-11 15:12
Pretty sure this is not a bug.  It is a warning.  I vaguely recall weird situations where `@PATH` from `Env` might have an undef it it.  I am pretty sure that it is harmless.

**Comment by wbraswell** [comment] 2017-01-12 08:41
https://github.com/Perl5-Alien/Alien-Base/pull/172

**Comment by plicease** [comment] 2017-01-18 08:34
Fix for this is in the repo, and will be included in the next release.

**Closed by plicease** 2017-01-18 08:34 UTC

**Comment by wbraswell** [comment] 2017-01-18 08:37
:+1:
